### ISSUE TITLE
Build ended in error

### ISSUE THREAD

**Issue by joewiz** [evolvedbinary/pebble#17]
Following the steps in the README, and using macOS 10.14.2), the final step `yarn && yarn build && yarn package` ended in the following error (though the app in `dist/mac` is launchable):

```
Error: ENOENT: no such file or directory, stat '/Users/joe/workspace/pebble/resources/dmgInstaller.tiff'
    at /Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/targets/dmg.ts:247:30
    at Generator.next (<anonymous>)
From previous event:
    at computeAssetSize (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/out/targets/dmg.js:49:22)
    at /Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/targets/dmg.ts:37:29
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/out/targets/dmg.js:253:11)
    at taskManager.addTask.default.map.it (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/platformPackager.ts:119:67)
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/platformPackager.ts:119:23)
    at /Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/macPackager.ts:95:26
    at processImmediate (timers.js:632:19)
From previous event:
    at /Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/macPackager.ts:95:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/out/macPackager.js:219:11)
    at /Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/joe/workspace/pebble/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/joe/workspace/pebble/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:161:5)
From previous event:
    at Packager.doBuild (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /Users/joe/workspace/pebble/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/joe/workspace/pebble/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
From previous event:
    at Packager._build (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /Users/joe/workspace/pebble/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/joe/workspace/pebble/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /Users/joe/workspace/pebble/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/joe/workspace/pebble/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/joe/workspace/pebble/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/Users/joe/workspace/pebble/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at processImmediate (timers.js:632:19)
From previous event:
    at Object.args [as handler] (/Users/joe/workspace/pebble/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/joe/workspace/pebble/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/joe/workspace/pebble/node_modules/electron-builder/node_modules/yargs/yargs.js:1074:24)
    at Object.get [as argv] (/Users/joe/workspace/pebble/node_modules/electron-builder/node_modules/yargs/yargs.js:989:21)
    at Object.<anonymous> (/Users/joe/workspace/pebble/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by joewiz** [comment]
@adamretter I can confirm the error is now gone, thanks!
